name: 'Setup Claude Code SDK'
description: 'Setup Node.js and Claude Code SDK'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Claude Code SDK
      shell: bash
      run: npm install -g @anthropic-ai/claude-code