name: module-fetch-data

on:
  workflow_call:
    inputs:
      product_name:
        required: true
        type: string
      sheets_id:
        required: true
        type: string
    outputs:
      completed:
        value: ${{ jobs.fetch.outputs.completed }}
    secrets:
      google_service_account_json:
        required: true
      anthropic_api_key:
        required: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      completed: ${{ steps.execute.outputs.completed }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: mkdir -p "${{ inputs.product_name }}/data"
      
      - id: execute
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.google_service_account_json }}
          GOOGLE_SHEETS_ID: ${{ inputs.sheets_id }}
        run: |
          # Pythonスクリプトを使用してデータを取得
          python .github/scripts/python/fetch_sheets_data.py "${{ inputs.product_name }}" | \
          while read line; do
            echo "$line" >> $GITHUB_OUTPUT
          done
          
          # 成功確認
          if [ -f "${{ inputs.product_name }}/data/market_bestsellers.csv" ]; then
            echo "completed=true" >> $GITHUB_OUTPUT
          else
            echo "completed=false" >> $GITHUB_OUTPUT
          fi
